 # Predicting Car Prices

## 1. Business Problem

We work for a used-car marketplace. A seller uploads a car (Make, Colour, Doors, Odometer) and we want to suggest a fair **Price**.

- **Why regression?** The target `Price` is a *continuous number*, not a category.
- **Business use:** auto-suggest listing prices, flag over/under-priced cars, estimate inventory value.

## 2. Explore the Data

Before any model: look at the data. Shape, features, target, and column types.

In [30]:
# Standard imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import sklearn
print(f"Using Scikit-Learn version: {sklearn.__version__}")

Using Scikit-Learn version: 1.9.0

In [31]:
# Load the clean version first
car_sales = pd.read_csv("../data/car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [32]:
car_sales.shape      # rows (samples), columns (features)

(1000, 5)

In [33]:
car_sales.dtypes     # which columns are NOT numbers?

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price            int64
dtype: object

**Observations:** `Make` and `Colour` are `object` (text). `Doors`, `Odometer (KM)`, `Price` are numeric.
Target = `Price`. Features = everything else. The text columns are the problem — a model can't multiply 'Toyota'.

**Ask students:** Which columns aren't numbers? Is `Doors` a quantity or a category?

## 3. Prepare the Data

### A. Separate X and y

X = inputs the model sees. y = the answer it predicts.

In [34]:
# X = features (everything except the answer), y = target
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

### B. Show *why* raw data fails (this cell errors on purpose)

Let it fail — it's the best teaching moment in the project.

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)   # ValueError: could not convert string to float: 'Toyota'

ValueError: could not convert string to float: 'Toyota'

`could not convert string to float` — the model is math, math needs numbers. **This is why the whole 'Prepare' phase exists.**

### C. Handle Missing Values

Switch to the realistic version (same data, with holes = `NaN`). Models refuse to train with missing values, so we **drop** or **fill** (impute).

**Rule:** the target is sacred — if a row is missing its `Price`, drop it (never invent the answer). Missing *features* we fill intelligently.

In [36]:
car_sales_missing = pd.read_csv("../data/car-sales-extended-missing-data.csv")

# How many holes, and where?
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [37]:
# Rule: never invent the answer. Drop rows missing the target (Price).
car_sales_missing.dropna(subset=["Price"], inplace=True)

# Re-split into X and y on the cleaned data
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

Different column types deserve different fills:
- **Text** (`Make`, `Colour`): constant word `"missing"` — treat unknown as its own category.
- **Doors**: constant `4` — most cars have 4 doors.
- **Odometer** (a measurement): the column **mean**.

In [38]:
from sklearn.impute import SimpleImputer

cat_imputer  = SimpleImputer(strategy="constant", fill_value="missing")  # Make, Colour
door_imputer = SimpleImputer(strategy="constant", fill_value=4)          # Doors
num_imputer  = SimpleImputer(strategy="mean")                            # Odometer (KM)

### D. Convert Categories to Numbers (One-Hot Encoding)

Don't map Toyota=1, Honda=2, BMW=3 — that invents a fake ordering the model will misuse.
**One-Hot Encoding** makes each category its own 0/1 column. Quick illustration with pandas:

Sample   Honda toyata BMW 
0         1    0      0
1         0    1      0
2         0    0       1

In [40]:
# Illustration of what one-hot encoding produces
dummies = pd.get_dummies(data=car_sales[["Make", "Colour", "Doors"]], dtype=float)
dummies.head()

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,5,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [41]:
car_sales["Doors"]= car_sales["Doors"].astype(object)
dummies = pd.get_dummies(data=car_sales[["Make", "Colour", "Doors"]], dtype=float)
dummies.head()

,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White,Doors_3,Doors_4,Doors_5
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

One text column exploded into several 0/1 columns. We'll do this properly with sklearn's `OneHotEncoder` inside the pipeline (so it's reusable on new data).

### E. Apply Transformations with ColumnTransformer

Different columns need different recipes. **ColumnTransformer** routes each transformer to the right columns in one object.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot", 
                                  one_hot, 
                                  categorical_features)],
                                remainder="passthrough",
                                sparse_threshold=0) # return a sparse matrix or not

transformed_X_missing = transformer.fit_transform(X_missing)
transformed_X_missing

In [45]:
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour"]
door_feature         = ["Doors"]
numerical_feature    = ["Odometer (KM)"]

# Route each group of columns to the right imputer
imputer = ColumnTransformer([
    ("cat_imputer",  cat_imputer,  categorical_features),
    ("door_imputer", door_imputer, door_feature),
    ("num_imputer",  num_imputer,  numerical_feature)])

In [47]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

## 4. Train/Test Split & Data Leakage

Split into a **training set** (model learns) and a **test set** (model is graded, never seen). Typically 80/20.

**Data leakage:** if the imputer learns its mean from the *whole* dataset (including test rows), test info leaks into preprocessing and the score becomes a lie.

**The rule:** preprocessing must `fit` on the training set only.
- `fit_transform(X_train)` → **learn** the fills **and** apply them — train only.
- `transform(X_test)` → **apply** what was learned — test only.

In [52]:
from sklearn.model_selection import train_test_split

np.random.seed(42)  # reproducibility
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# fit_transform on TRAIN: the imputer LEARNS the means/fills here...
filled_X_train = imputer.fit_transform(X_train)

# transform ONLY on TEST: it just APPLIES what it learned from train.
filled_X_test  = imputer.transform(X_test)
filled_X_train[:3]

array([['Honda', 'White', 4.0, 71934.0],
       ['Toyota', 'Red', 4.0, 162665.0],
       ['Honda', 'White', 4.0, 42844.0]], dtype=object)

## 5. Build a Preprocessing Pipeline

Doing impute -> encode -> split by hand is fragile. A **Pipeline** chains steps into one object, and `.fit()` automatically fits every step on training data only.

**This is how preprocessing is done in real projects.**

In [53]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Load fresh and drop rows with no target
data = pd.read_csv("../data/car-sales-extended-missing-data.csv")
data.dropna(subset=["Price"], inplace=True)

# Each column-group gets a mini-pipeline: fill, then (if text) one-hot
categorical_features = ["Make", "Colour"]
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value="missing")),
    ("onehot",  OneHotEncoder(handle_unknown="ignore"))])

door_feature = ["Doors"]
door_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="constant", fill_value=4))])

numeric_features = ["Odometer (KM)"]
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean"))])

# Combine them: route each group to its mini-pipeline
preprocessor = ColumnTransformer(transformers=[
    ("cat",  categorical_transformer, categorical_features),
    ("door", door_transformer,        door_feature),
    ("num",  numeric_transformer,     numeric_features)])

# Bolt the model on the end -> ONE object that does everything
model = Pipeline(steps=[("preprocessor", preprocessor),
                        ("model", RandomForestRegressor(n_jobs=-1))])
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Make', 'Colour']),
                                                 ('door',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value=4,
                                                                                 strategy='constant'))]),
                                                  ['Doors']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  ['Odometer (KM)'])])),
                ('model', RandomForestRegressor(n_jobs=-1))])

## 6. Train the Model

`.fit()` is where learning happens — it walks every training example and adjusts the model so its price guesses get closer to the truth. Because `model` is the whole pipeline, this one call imputes, encodes, **and** trains — on training data only.

In [54]:
X = data.drop("Price", axis=1)
y = data["Price"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model.fit(X_train, y_train)   # preprocess + learn, in one call

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Make', 'Colour']),
                                                 ('door',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value=4,
                                                                                 strategy='constant'))]),
                                                  ['Doors']),
                                                 ('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer())]),
                                                  ['Odometer (KM)'])])),
                ('model', RandomForestRegressor(n_jobs=-1))])

## 7. Evaluate the Model

For regression: **MAE, MSE, RMSE, R²**. `.score()` on a regressor returns **R²**.

In [57]:
# Quick health check - for a regressor, .score() returns R^2
model.score(X_test, y_test)

0.22188417408787864

In [58]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_preds = model.predict(X_test)

mae  = mean_absolute_error(y_test, y_preds)
mse  = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)
r2   = r2_score(y_test, y_preds)

print(f"R2:   {r2:.3f}")
print(f"MAE:  {mae:.2f}")
print(f"MSE:  {mse:.2f}")
print(f"RMSE: {rmse:.2f}")

R2:   0.222
MAE:  5713.17
MSE:  52102396.83
RMSE: 7218.20

- **MAE** — average dollar error. Readable; doesn't punish big misses extra.
- **MSE** — average squared error (dollars²). Punishes big errors; not human-readable.
- **RMSE** — root of MSE, back in dollars. Readable *and* punishes big errors. A big RMSE–MAE gap = a few large errors.
- **R²** — fraction of price variation explained. 1=perfect, 0=no better than guessing the mean price. Pair it with MAE/RMSE.

## 8. Improve the Model

Never marry your first model. Two levers: try a different **algorithm**, and tune **hyperparameters**.

In [59]:
from sklearn.linear_model import LinearRegression

# Same preprocessor, different model on the end
lin_model = Pipeline(steps=[("preprocessor", preprocessor),
                            ("model", LinearRegression())])
lin_model.fit(X_train, y_train)
print(f"LinearRegression R2: {lin_model.score(X_test, y_test):.3f}")
print(f"RandomForest     R2: {model.score(X_test, y_test):.3f}")

LinearRegression R2: 0.253
RandomForest     R2: 0.222

In [60]:
from sklearn.model_selection import GridSearchCV

# Note the double-underscore path: pipelineStep__subStep__param
pipe_grid = {
    "preprocessor__num__imputer__strategy": ["mean", "median"],
    "model__n_estimators": [100, 1000],
    "model__max_depth": [None, 5],
    "model__max_features": ["sqrt"],
    "model__min_samples_split": [2, 4],
}

gs_model = GridSearchCV(model, pipe_grid, cv=5, verbose=2)
gs_model.fit(X_train, y_train)
gs_model.score(X_test, y_test)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.0s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.5s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.5s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.4s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  10.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  12.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  10.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  10.4s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.6s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  10.7s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  10.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  10.4s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.0s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.9s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.5s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.9s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.8s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  10.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  11.2s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  15.1s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  14.7s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  13.5s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  12.4s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.0s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   8.3s
[CV] END model__max_depth=None, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   8.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.8s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.8s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  18.5s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  16.3s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  14.6s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  13.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  13.7s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=  10.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   8.6s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.6s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=2, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   8.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.9s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   1.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.8s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=mean; total time=   0.8s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   0.8s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=100, preprocessor__num__imputer__strategy=median; total time=   1.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.7s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   8.1s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=  10.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=mean; total time=   9.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.0s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   9.2s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   6.4s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   6.5s
[CV] END model__max_depth=5, model__max_features=sqrt, model__min_samples_split=4, model__n_estimators=1000, preprocessor__num__imputer__strategy=median; total time=   6.8s

0.2848784564026806

In [67]:
gs_model.best_params_

{'model__max_depth': 5,
 'model__max_features': 'sqrt',
 'model__min_samples_split': 2,
 'model__n_estimators': 100,
 'preprocessor__num__imputer__strategy': 'mean'}

## 9. Save the Model

Serialize the trained pipeline so the app can load and predict instantly. **pickle** (built-in) or **joblib** (faster for big models).

In [61]:
import pickle

# Save the WHOLE pipeline (preprocessing + model together)
pickle.dump(gs_model, open("car_price_model.pkl", "wb"))

loaded = pickle.load(open("car_price_model.pkl", "rb"))
print(f"Loaded model R2: {loaded.score(X_test, y_test):.3f}")

Loaded model R2: 0.285

In [62]:
from joblib import dump, load

dump(gs_model, "car_price_model.joblib")
loaded_joblib = load("car_price_model.joblib")
print(f"Loaded joblib model R2: {loaded_joblib.score(X_test, y_test):.3f}")

Loaded joblib model R2: 0.285

In [75]:
# A brand-new listing comes in - RAW data, exactly like the CSV.
# Note: Doors is given as 4.0 (float) so its dtype matches the training
# data, where Doors became float because that column contained missing values.
new_car = pd.DataFrame({
    "Make": ["Toyota"],
    "Colour": ["White"],
    "Odometer (KM)": [55000],
    "Doors": [4.0],
})
print(f"Suggested price: ${loaded.predict(new_car)[0]:,.0f}")

Suggested price: $19,054

Because we saved the *whole pipeline*, the loaded model imputes and encodes this raw car automatically. **That's the payoff of preprocessing inside the pipeline.**